server:
  port: 7001

eureka:
  server:
    #关闭自我保护
    enable-self-preservation: false
    #发送心跳时间  默认是90s
    eviction-interval-timer-in-ms: 2000
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称  localhost 要改成  eureka7001.com 需要去hosts文件进行配置
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #集群模式
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机
      defaultZone: http://eureka7001.com:7001/eureka/




